#pragma once

#include <windows.h>

#include <optional>

struct HeadPose
{
    double pitch = 0.0;
    double yaw = 0.0;
    double roll = 0.0;

    // Raw OpenXR orientation. Keeping the quaternion alongside the convenience
    // Euler angles lets the Phase 3B weapon rig reproduce the controller pose
    // without gimbal-lock or startup-pose assumptions.
    double qx = 0.0;
    double qy = 0.0;
    double qz = 0.0;
    double qw = 1.0;

    // OpenXR LOCAL-space position in meters: +X right, +Y up, -Z forward.
    double x = 0.0;
    double y = 0.0;
    double z = 0.0;

    bool orientationValid = false;
    bool positionValid = false;
};

using ControllerPose = HeadPose;

struct TouchControllerState
{
    ControllerPose leftAim{};
    ControllerPose rightAim{};
    ControllerPose leftGrip{};
    ControllerPose rightGrip{};

    float leftTrigger = 0.0f;
    float rightTrigger = 0.0f;
    float leftGripValue = 0.0f;
    float rightGripValue = 0.0f;
    float leftThumbX = 0.0f;
    float leftThumbY = 0.0f;
    float rightThumbX = 0.0f;
    float rightThumbY = 0.0f;

    bool leftStickClick = false;
    bool rightStickClick = false;
    bool leftPrimary = false;   // X on Oculus Touch
    bool leftSecondary = false; // Y on Oculus Touch
    bool rightPrimary = false;  // A on Oculus Touch
    bool rightSecondary = false;// B on Oculus Touch
    bool menu = false;
    bool available = false;
};

class OpenXRHeadset
{
public:
    OpenXRHeadset();
    ~OpenXRHeadset();

    OpenXRHeadset(const OpenXRHeadset&) = delete;
    OpenXRHeadset& operator=(const OpenXRHeadset&) = delete;

    bool Initialize();
    bool PollEvents();

    // Waits for the next OpenXR frame, returns the tracked HMD pose and, when a
    // usable game window is supplied, submits a captured campaign frame to both
    // headset eyes. Phase 2B preserves the Rift optical-center correction.
    std::optional<HeadPose> WaitForPoseAndRender(HWND gameWindow);

    // Latest OpenXR Touch state synchronized alongside the rendered frame.
    TouchControllerState Controllers() const;

    bool IsEyeRenderingActive() const;

private:
    // Phase 3A wraps the known-good Phase 2B implementation rather than
    // replacing its renderer. These base methods are generated by the wrapper
    // translation unit from OpenXRHeadsetOpticalCenter.cpp.
    bool InitializeBase();
    std::optional<HeadPose> WaitForPoseAndRenderBase(HWND gameWindow);

    struct Impl;
    Impl* impl_ = nullptr;
};
